variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

  GIT_DEPTH: 0  # 0 means full clone

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_REF_NAME"'

cache:
  paths:
    - .m2/repository

#Definition des différentes étapes présent dans le pipeline
stages:
  - build   # compilation
  - test    # exécution des tests
  - package # empaquetage


#Définition du job de compilation
compilation:
  image: maven:3.8.5-openjdk-17
  stage: build
  script:
    # On compile le projet avec Maven Wrapper
    - ./mvnw $MAVEN_CLI_OPTS compile

#Définition du job de validation (tests unitaires)
validation:
  image: maven:3.8.5-openjdk-17
  stage: test
  script:
    # Exécuter les tests avec JaCoCo
    - ./mvnw $MAVEN_CLI_OPTS test
    # Extraire le pourcentage de couverture depuis le fichier HTML
    - COVERAGE=$(grep -Po 'Total.*?([0-9]{1,3})%' target/site/jacoco/index.html | grep -Po '[0-9]{1,3}' | tail -1)
    - echo "Total $COVERAGE%"
  coverage: '/Total.*?([0-9]{1,3})%/'
  artifacts:
    when: always
    reports:
      junit: target/surefire-reports/*.xml
    paths:
      - target/site/jacoco/jacoco.xml  # keep the file so sonar_scan can read it


#Définition du job de packaging (génération du JAR)
packaging:
  image: maven:3.8.5-openjdk-17
  stage: package
  script:
    - ./mvnw $MAVEN_CLI_OPTS package
  artifacts:
    paths:
      - target/*.jar

